<?php
return [
    'RUS'=> 'RUSSIAN FEDERATION',
    'ARM'=> 'ARMENIA',
    'AZE'=> 'AZERBAIJAN',
    'GEO'=> 'GEORGIA',
    'UKR'=> 'UKRAINE',
    'BLR'=> 'BELARUS',
    'MDA'=> 'MOLDOVA',
    'UZB'=> 'UZBEKISTAN',
    'KAZ'=> 'KAZAKHSTAN',
    'KGZ'=> 'KYRGYZSTAN',
    'TKM'=> 'TURKMENISTAN',
    'LVA'=> 'LATVIA',
    'LTU'=> 'LITHUANIA ',
    'EST'=> 'ESTONIA',
    'HUN'=> 'HUNGARY',
    'DEU'=> 'GERMANY',
    'TUR'=> 'TURKEY',
    'USA'=> 'USA',
    'GBR'=> 'UNITED KINGDOM',
    'ARE'=> 'UNITED ARAB EMIRATES',
    'AUT'=> 'AUSTRIA',
    'POL'=> 'POLAND',
    'IRN'=> 'IRAN',
    'CZE'=> 'CZECH REPUBLIC',
    'SRB'=> 'SERBIA',
];
